<a href="https://colab.research.google.com/github/GolfSuradej/IrisPAD/blob/main/Iris_2D3D_Fusion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import os
import numpy as np
from google.colab import drive
import h5py
from tensorflow import keras
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Import Data

In [ ]:
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
cd /content/drive/MyDrive/Seniorsource

/content/drive/MyDrive/Seniorsource


BSIF Feature Extration

In [ ]:
myrealFeature = np.load("realmyBISF.npy")

In [ ]:
np.transpose(myrealFeature[0])
print("No. of the Samples : " ,len(myrealFeature))
print("Feature length : ",len(myrealFeature[0]))

No. of the Samples :  246
Feature length :  32


In [ ]:
myfakeFeature = np.load("fakemyBISF.npy")

In [ ]:
np.transpose(myfakeFeature[0])
print("No. of the Samples : " ,len(myfakeFeature))
print("Feature length : ",len(myfakeFeature[0]))

No. of the Samples :  440
Feature length :  32


In [ ]:
trainmyrealFeature = myrealFeature
trainmyfakeFeature = myfakeFeature

In [ ]:
#trainmyrealFeature = np.load("realtrainmyBISF.npy")
np.transpose(trainmyrealFeature[0])
print("No. of the Samples : " ,len(trainmyrealFeature))
print("Feature length : ",len(trainmyrealFeature[0]))

No. of the Samples :  246
Feature length :  32


In [ ]:
#np.load("faketrainmyBISF.npy")
np.transpose(trainmyfakeFeature[0])
print("No. of the Samples : " ,len(trainmyfakeFeature))
print("Feature length : ",len(trainmyfakeFeature[0]))

No. of the Samples :  440
Feature length :  32


Label

In [ ]:
#RX = myrealFeature[0:246]  #Golf
#RY = np.zeros([246,1]) #Golf
RX = myrealFeature
RY = np.zeros([len(trainmyrealFeature),1])
#print(np.transpose(RY)) #golf

In [ ]:
#FX = myfakeFeature[0:440] #golf
#FY = np.ones([440,1])
FY = np.ones([len(trainmyfakeFeature),1])
FX = myfakeFeature
#print(np.transpose(FY))

In [ ]:
RX_train = trainmyrealFeature[0:270]
RY_train = np.zeros([270,1])
print(np.transpose(RY_train))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]]


In [ ]:
FX_train = trainmyfakeFeature[0:400]
FY_train = np.ones([400,1])
print(np.transpose(FY_train))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 

In [ ]:
A = np.vstack((FX_train,RX_train))
print(A.shape)
C = np.vstack((FX,RX))
print(C.shape)

(646, 32, 1)
(686, 32, 1)


In [ ]:
B = np.vstack((FY_train,RY_train))
print(B.shape)
D = np.vstack((FY,RY))
print(D.shape)

(670, 1)
(686, 1)


In [ ]:
X, Y = shuffle(A,B)
np.save('X_train',X)
np.save('Y_train',Y)
TX, TY = shuffle(C,D)
np.save('X_test',TX)
np.save('Y_test',TY)

ValueError: ignored

In [ ]:
x = X.reshape(len(X),32)
y = Y.reshape(len(Y),1)
tx = TX.reshape(len(TX),32)
ty = TY.reshape(len(TY),1)
print(x.shape)
print(y.shape)
print(tx.shape)
print(ty.shape)

(670, 32)
(670, 1)
(670, 32)
(670, 1)


In [ ]:
print(np.transpose(y[0:10]))

[[1. 1. 1. 0. 1. 1. 0. 1. 1. 1.]]


SVM

In [ ]:
from sklearn import svm
# import metrics to compute accuracy
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
clf = svm.SVC(kernel='linear') # instantiate classifier with default hyperparameters

Train or fitting the model

In [ ]:
clf.fit(x,y)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [ ]:
clf.predict(x[0].reshape(1,32))

In [ ]:
clf.predict(x[1].reshape(1,32))

In [ ]:
out = np.zeros([len(tx),1])
for i in range(len(tx)):
  out[i] = clf.predict(tx[i].reshape(1,32))

In [ ]:
from scipy.optimize import brentq
from scipy.interpolate import interp1d
from sklearn.metrics import roc_curve
from sklearn.metrics import precision_score

fpr, tpr, thresholds = roc_curve(ty, out, pos_label=1)

def compute_eer(fpr,tpr,thresholds):
    """ Returns equal error rate (EER) and the corresponding threshold. """
    fnr = 1-tpr
    print(fnr)
    abs_diffs = np.abs(fpr - fnr)
    min_index = np.argmin(abs_diffs)
    eer = np.mean((fpr[min_index], fnr[min_index]))
    return eer, thresholds[min_index]
    
err,thr = compute_eer(fpr, tpr, thresholds)
print(err)
print(thr)



In [ ]:
accuracy_score(ty, out)

0.6457725947521866

In [ ]:
clf =  svm.SVC(kernel='linear',probability=True)
clf.fit(x, y)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', probability=True)

In [ ]:
print(clf.predict_proba(x[0].reshape(1,32)))

[[0.03445482 0.96554518]]


In [ ]:
print(clf.predict_proba(x[18].reshape(1,32)))

[[0.9383835 0.0616165]]


In [ ]:
y[18]

array([0.])

In [ ]:
x

NameError: ignored