<a href="https://colab.research.google.com/github/GolfSuradej/IrisPAD/blob/main/Test_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import os
import numpy as np
from google.colab import drive
import h5py
from tensorflow import keras
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

Import Data

In [ ]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
cd /content/drive/MyDrive/Seniorsource

/content/drive/MyDrive/Seniorsource


BSIF Feature Extration

In [ ]:
myrealFeature = np.load("realmyBISF.npy")

In [ ]:
np.transpose(myrealFeature[0])

array([[330551.,   3261.,   8532.,   3401.,   2803.,   2876.,   3274.,
          2375.,   3634.,  13465.,   3232.,   9898.,   2647.,   5305.,
          1731.,   3421.,   1972.,   1835.,   4209.,   3369.,   5771.,
          2723.,  10363.,   2727.,   2431.,   4559.,   2698.,   4025.,
          2346.,   9845.,   2414.,   6307.]])

In [ ]:
myfakeFeature = np.load("fakemyBISF.npy")

In [ ]:
np.transpose(myfakeFeature[0])

array([[11231., 17967., 14116., 13960., 12190., 25054., 13469., 20449.,
        13546., 15411., 17627., 11514., 16283., 15396., 17907., 13432.,
        11434., 18310., 13382., 15668.,  8498., 12757., 11008.,  9851.,
        20647., 15464., 24529., 14402., 10288., 10646., 12996.,  8568.]])

In [ ]:
print("No. of the Samples : " ,len(myrealFeature))
print("Feature length : ",len(myrealFeature[0]))

No. of the Samples :  246
Feature length :  32


In [ ]:
print("No. of the Samples : " ,len(myfakeFeature))
print("Feature length : ",len(myfakeFeature[0]))

No. of the Samples :  440
Feature length :  32


Label

In [ ]:
RX_train = myrealFeature[0:246]
RY_train = np.zeros([246,1])
print(np.transpose(RY_train))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]]


In [ ]:
FX_train = myfakeFeature[0:440]
FY_train = np.ones([440,1])
print(np.transpose(FY_train))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 

In [ ]:
A = np.vstack((FX_train,RX_train))
print(A.shape)

(686, 32, 1)


In [ ]:
B = np.vstack((FY_train,RY_train))
print(B.shape)

(686, 1)


SVM

In [ ]:
from sklearn import svm
# import metrics to compute accuracy
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
clf = svm.SVC() # instantiate classifier with default hyperparameters

In [ ]:
A_train, A_test, B_train, B_test = train_test_split(A, B, test_size=0.20, random_state=None, shuffle=True)
print(A_train)

[[[330551.]
  [  3261.]
  [  8532.]
  ...
  [  9845.]
  [  2414.]
  [  6307.]]

 [[ 13379.]
  [ 20503.]
  [ 17862.]
  ...
  [ 12006.]
  [ 11773.]
  [  8889.]]

 [[ 17552.]
  [ 17036.]
  [ 18452.]
  ...
  [ 11425.]
  [ 12271.]
  [  8905.]]

 ...

 [[ 15404.]
  [ 14751.]
  [ 19869.]
  ...
  [ 16172.]
  [ 12441.]
  [ 16164.]]

 [[355803.]
  [  2634.]
  [  7283.]
  ...
  [  8997.]
  [  2974.]
  [  5340.]]

 [[167211.]
  [  8180.]
  [ 16457.]
  ...
  [ 18110.]
  [  9277.]
  [ 13104.]]]


In [ ]:
# Making the SVM Classifer
Classifier = SVC(kernel="linear")

# Training the model on the training data and labels
Classifier.fit(A_train, B_train)

# Using the model to predict the labels of the test data
B_pred = Classifier.predict(A_test)

# Evaluating the accuracy of the model using the sklearn functions
accuracy = accuracy_score(B_test,B_pred)*100
confusion_mat = confusion_matrix(B_test,B_pred)

# Printing the results
print("Accuracy for SVM is:",accuracy)
print("Confusion Matrix")
print(confusion_mat)

ValueError: ignored